apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ry-ta2647-nextproject
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/ry-ta2647-nextproject.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ry-ta2647-nextproject
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
