apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ry-ta2647-nextproject-certificate
  namespace: ry-ta2647-nextproject
spec:
  secretName: ry-ta2647-nextproject-secret-tls
  commonName: ry-ta2647-nextproject.assessify.org
  dnsNames:
  - ry-ta2647-nextproject.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
